'use client';

import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import { Eye, ExternalLink, MoreHorizontal, Pencil, ChevronLeft, ChevronRight } from 'lucide-react';
import Link from 'next/link';
import type { Client } from '../../types/clients';

const dateFormatter = new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'short', year: 'numeric' });
function date(value: string) { return dateFormatter.format(new Date(value)); }

export function ClientTable({ clients, page, totalPages, total, onPage, onEdit }: { clients: Client[]; page: number; totalPages: number; total: number; onPage: (page: number) => void; onEdit: (client: Client) => void }) {
  return <div className="overflow-hidden rounded-xl border border-[var(--border-subtle)] bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[var(--border)] bg-[var(--surface-secondary)] text-xs uppercase tracking-wide text-[var(--muted-foreground)]"><tr>{['Cliente', 'Empresa', 'Contacto', 'Origen', 'Convertido', ''].map((label) => <th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--border)]">{clients.map((client) => <tr key={client.id} className="transition-colors hover:bg-[var(--surface-secondary)]"><td className="px-4 py-3"><Link href={`/clientes/${client.id}`} className="font-semibold hover:text-[var(--primary)] hover:underline">{client.name}</Link></td><td className="px-4 py-3 text-[var(--muted-foreground)]">{client.company || '—'}</td><td className="px-4 py-3"><p>{client.email || 'Sin email'}</p><p className="text-[13px] text-[var(--muted-foreground)]">{client.phone || 'Sin teléfono'}</p></td><td className="px-4 py-3"><p>Lead</p><p className="text-[13px] text-[var(--muted-foreground)]">{client.sourceLead.source === 'WEBSITE' ? 'Sitio web' : client.sourceLead.source}</p></td><td className="whitespace-nowrap px-4 py-3 text-[13px] text-[var(--muted-foreground)]">{date(client.convertedAt)}</td><td className="px-2 py-3 text-right"><Actions client={client} onEdit={onEdit} /></td></tr>)}</tbody></table></div><div className="flex flex-col gap-3 border-t border-[var(--border)] px-4 py-3 text-sm text-[var(--muted-foreground)] sm:flex-row sm:items-center sm:justify-between"><span>{total} {total === 1 ? 'cliente' : 'clientes'}</span><div className="flex items-center gap-3"><span>Página {page} de {Math.max(totalPages, 1)}</span><button type="button" disabled={page <= 1} onClick={() => onPage(page - 1)} className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-[var(--border)] hover:bg-[var(--muted)] disabled:pointer-events-none disabled:opacity-40" aria-label="Página anterior"><ChevronLeft size={16} /></button><button type="button" disabled={page >= totalPages} onClick={() => onPage(page + 1)} className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-[var(--border)] hover:bg-[var(--muted)] disabled:pointer-events-none disabled:opacity-40" aria-label="Página siguiente"><ChevronRight size={16} /></button></div></div></div>;
}

function Actions({ client, onEdit }: { client: Client; onEdit: (client: Client) => void }) {
  const item = 'flex cursor-default select-none items-center gap-2 rounded-md px-2.5 py-2 text-sm outline-none data-[highlighted]:bg-[var(--muted)]';
  return <DropdownMenu.Root><DropdownMenu.Trigger asChild><button type="button" className="inline-flex h-8 w-8 items-center justify-center rounded-md text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Acciones del cliente"><MoreHorizontal size={18} /></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content side="bottom" align="end" sideOffset={6} collisionPadding={8} className="z-50 w-48 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-1 shadow-md"><DropdownMenu.Item asChild className={item}><Link href={`/clientes/${client.id}`}><Eye size={15} />Ver detalle</Link></DropdownMenu.Item><DropdownMenu.Item className={item} onSelect={() => onEdit(client)}><Pencil size={15} />Editar</DropdownMenu.Item><DropdownMenu.Separator className="my-1 h-px bg-[var(--border)]" /><DropdownMenu.Item asChild className={item}><Link href={`/leads/${client.sourceLeadId}`}><ExternalLink size={15} />Ver lead de origen</Link></DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>;
}
