'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { X } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import type { Client, ClientPayload } from '../../types/clients';
import { LEAD_LIMITS, normalizeLeadPhone } from '../../lib/lead-validation';

const schema = z.object({ name: z.string().trim().min(2, 'El nombre debe tener al menos 2 caracteres.').max(LEAD_LIMITS.name), company: z.string().trim().max(LEAD_LIMITS.company), email: z.string().trim().max(LEAD_LIMITS.email).refine((value) => !value || z.email().safeParse(value).success, 'Ingresa un email válido.'), phone: z.string().trim().refine((value) => !value || /^\+?[\d\s()-]{7,32}$/.test(value) && /^\+?\d{7,15}$/.test(normalizeLeadPhone(value)), 'Ingresa un teléfono válido.'), notes: z.string().trim().max(LEAD_LIMITS.notes) }).superRefine((data, context) => { if (!data.email && !data.phone) context.addIssue({ code: 'custom', path: ['email'], message: 'Debes indicar un correo o un teléfono.' }); });
type Values = z.infer<typeof schema>;

export function ClientForm({ client, loading, onClose, onSubmit }: { client: Client; loading: boolean; onClose: () => void; onSubmit: (payload: ClientPayload) => void }) {
  const { register, handleSubmit, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name: client.name, company: client.company || '', email: client.email || '', phone: client.phone || '', notes: client.notes || '' } });
  const field = (name: keyof Values, label: string, type = 'text') => <label className="block text-sm font-medium">{label}<input {...register(name)} type={type} className="mt-2 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-sm outline-none focus:border-[var(--primary)]" />{errors[name] && <span className="mt-1 block text-sm font-normal text-[var(--danger)]">{errors[name]?.message}</span>}</label>;
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="presentation" onClick={onClose}><div className="flex h-full w-full max-w-xl flex-col bg-[var(--surface)] shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="client-form-title" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-[var(--border)] px-6 py-6"><div><h2 id="client-form-title" className="text-xl font-semibold">Editar cliente</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Actualiza los datos de contacto.</p></div><button type="button" onClick={onClose} className="rounded-md p-2 text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Cerrar formulario"><X size={19} /></button></div><form onSubmit={handleSubmit((values) => onSubmit({ ...values, email: values.email.toLowerCase() || null, phone: values.phone ? normalizeLeadPhone(values.phone) : null, company: values.company || null, notes: values.notes || null }))} className="flex-1 space-y-5 overflow-y-auto px-6 py-7"><div className="grid gap-5 sm:grid-cols-2">{field('name', 'Nombre')}{field('company', 'Empresa')}{field('email', 'Email', 'email')}{field('phone', 'Teléfono')}</div><label className="block text-sm font-medium">Notas<textarea {...register('notes')} rows={6} className="mt-2 w-full resize-y rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 text-sm outline-none focus:border-[var(--primary)]" />{errors.notes && <span className="mt-1 block text-sm font-normal text-[var(--danger)]">{errors.notes.message}</span>}</label><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-6"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-[var(--border)] px-4 text-sm font-medium hover:bg-[var(--muted)]">Cancelar</button><button type="submit" disabled={loading} className="h-10 rounded-lg bg-[var(--primary)] px-5 text-sm font-semibold text-white hover:bg-[var(--primary-hover)] disabled:opacity-60">{loading ? 'Guardando...' : 'Guardar cambios'}</button></div></form></div></div>;
}
